package arm.node;

@:keep class EnemyDeath extends armory.logicnode.LogicTree {

	public function new() { super(); notifyOnAdd(add); }

	override public function add() {
		var _RemoveObject = new armory.logicnode.RemoveObjectNode(this);
		var _SpawnObject = new armory.logicnode.SpawnObjectNode(this);
		var _SetVisible = new armory.logicnode.SetVisibleNode(this);
		var _SetVariable_002 = new armory.logicnode.SetVariableNode(this);
		var _IsTrue = new armory.logicnode.IsTrueNode(this);
		var _Gate = new armory.logicnode.GateNode(this);
		_Gate.property0 = "Less Equal";
		_Gate.property1 = 9.999999747378752e-05;
		var _RemoveObject_003 = new armory.logicnode.RemoveObjectNode(this);
		var _Gate_001 = new armory.logicnode.GateNode(this);
		_Gate_001.property0 = "Equal";
		_Gate_001.property1 = 9.999999747378752e-05;
		var _Gate_003 = new armory.logicnode.GateNode(this);
		_Gate_003.property0 = "Greater";
		_Gate_003.property1 = 9.999999747378752e-05;
		var _OnUpdate_001 = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate_001.addOutputs([_Gate_003]);
		_Gate_003.addInput(_OnUpdate_001, 0);
		var _Float_002 = new armory.logicnode.FloatNode(this);
		_Float_002.addInput(new armory.logicnode.FloatNode(this, 20.0), 0);
		var _SetVariable_001 = new armory.logicnode.SetVariableNode(this);
		_SetVariable_001.addInput(_RemoveObject_003, 0);
		_SetVariable_001.addInput(_Float_002, 0);
		var _Math_004 = new armory.logicnode.MathNode(this);
		_Math_004.property0 = "Add";
		_Math_004.property1 = "false";
		_Math_004.addInput(_Float_002, 0);
		var _Math_003 = new armory.logicnode.MathNode(this);
		_Math_003.property0 = "Multiply";
		_Math_003.property1 = "false";
		var _GetProperty_001 = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject_001 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_001.addOutputs([_GetProperty_001]);
		_GetProperty_001.addInput(_GlobalObject_001, 0);
		_GetProperty_001.addInput(new armory.logicnode.StringNode(this, "PlayerDamage"), 0);
		_GetProperty_001.addOutputs([_Math_003]);
		_Math_003.addInput(_GetProperty_001, 0);
		_Math_003.addInput(new armory.logicnode.FloatNode(this, -1.0), 0);
		_Math_003.addOutputs([_Math_004]);
		_Math_004.addInput(_Math_003, 0);
		_Math_004.addOutputs([_SetVariable_001]);
		_SetVariable_001.addInput(_Math_004, 0);
		_SetVariable_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_Float_002.addOutputs([_SetVariable_001, _Math_004, _Gate, _Float_002]);
		_Gate_003.addInput(_Float_002, 0);
		var _Float = new armory.logicnode.FloatNode(this);
		_Float.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Float.addOutputs([_Gate_003]);
		_Gate_003.addInput(_Float, 0);
		_Gate_003.addOutputs([_Gate_001]);
		_Gate_003.addOutputs([new armory.logicnode.NullNode(this)]);
		_Gate_001.addInput(_Gate_003, 0);
		var _GetParent_001 = new armory.logicnode.GetParentNode(this);
		var _ArrayGet = new armory.logicnode.ArrayGetNode(this);
		var _GetContacts = new armory.logicnode.GetContactsNode(this);
		var _Self_002 = new armory.logicnode.SelfNode(this);
		var _RemoveObject_001 = new armory.logicnode.RemoveObjectNode(this);
		var _Sleep_001 = new armory.logicnode.SleepNode(this);
		var _OnInit = new armory.logicnode.OnInitNode(this);
		_OnInit.addOutputs([_Sleep_001]);
		_Sleep_001.addInput(_OnInit, 0);
		_Sleep_001.addInput(new armory.logicnode.FloatNode(this, 20.0), 0);
		_Sleep_001.addOutputs([_RemoveObject_001]);
		_RemoveObject_001.addInput(_Sleep_001, 0);
		_RemoveObject_001.addInput(_Self_002, 0);
		_RemoveObject_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_Self_002.addOutputs([_RemoveObject_001, _GetContacts]);
		_GetContacts.addInput(_Self_002, 0);
		var _ArrayLength = new armory.logicnode.ArrayLengthNode(this);
		_ArrayLength.addInput(_GetContacts, 0);
		var _Math_005 = new armory.logicnode.MathNode(this);
		_Math_005.property0 = "Subtract";
		_Math_005.property1 = "false";
		_Math_005.addInput(_ArrayLength, 0);
		_Math_005.addInput(new armory.logicnode.FloatNode(this, 1.0), 0);
		_Math_005.addOutputs([_ArrayGet]);
		_ArrayLength.addOutputs([_Math_005]);
		_GetContacts.addOutputs([_ArrayLength, _ArrayGet]);
		_ArrayGet.addInput(_GetContacts, 0);
		_ArrayGet.addInput(_Math_005, 0);
		_ArrayGet.addOutputs([_GetParent_001, _RemoveObject_003]);
		_GetParent_001.addInput(_ArrayGet, 0);
		_GetParent_001.addOutputs([_Gate_001]);
		_Gate_001.addInput(_GetParent_001, 0);
		var _Object_001 = new armory.logicnode.ObjectNode(this);
		_Object_001.addInput(new armory.logicnode.ObjectNode(this, "PlayerLasers"), 0);
		_Object_001.addOutputs([_Gate_001]);
		_Gate_001.addInput(_Object_001, 0);
		_Gate_001.addOutputs([_RemoveObject_003]);
		_Gate_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_RemoveObject_003.addInput(_Gate_001, 0);
		_RemoveObject_003.addInput(_ArrayGet, 0);
		_RemoveObject_003.addOutputs([_SetVariable_001, _Gate]);
		_Gate.addInput(_RemoveObject_003, 0);
		_Gate.addInput(_Float_002, 0);
		var _Float_003 = new armory.logicnode.FloatNode(this);
		_Float_003.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Float_003.addOutputs([_Gate]);
		_Gate.addInput(_Float_003, 0);
		_Gate.addOutputs([_IsTrue]);
		_Gate.addOutputs([new armory.logicnode.NullNode(this)]);
		_IsTrue.addInput(_Gate, 0);
		var _Boolean = new armory.logicnode.BooleanNode(this);
		_Boolean.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_Boolean.addOutputs([_IsTrue, _SetVariable_002]);
		_IsTrue.addInput(_Boolean, 0);
		_IsTrue.addOutputs([_SetVariable_002]);
		_SetVariable_002.addInput(_IsTrue, 0);
		_SetVariable_002.addInput(_Boolean, 0);
		var _Boolean_001 = new armory.logicnode.BooleanNode(this);
		_Boolean_001.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_Boolean_001.addOutputs([_SetVariable_002]);
		_SetVariable_002.addInput(_Boolean_001, 0);
		_SetVariable_002.addOutputs([_SetVisible]);
		_SetVisible.addInput(_SetVariable_002, 0);
		var _Self_003 = new armory.logicnode.SelfNode(this);
		var _GetTransform = new armory.logicnode.GetTransformNode(this);
		_GetTransform.addInput(_Self_003, 0);
		_GetTransform.addOutputs([_SpawnObject]);
		_Self_003.addOutputs([_GetTransform, _RemoveObject, _SetVisible]);
		_SetVisible.addInput(_Self_003, 0);
		var _Boolean_002 = new armory.logicnode.BooleanNode(this);
		_Boolean_002.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_Boolean_002.addOutputs([_SetVisible]);
		_SetVisible.addInput(_Boolean_002, 0);
		_SetVisible.addOutputs([_SpawnObject]);
		_SpawnObject.addInput(_SetVisible, 0);
		_SpawnObject.addInput(new armory.logicnode.ObjectNode(this, "ENimi0-Explosion"), 0);
		_SpawnObject.addInput(_GetTransform, 0);
		_SpawnObject.addOutputs([_RemoveObject]);
		_SpawnObject.addOutputs([new armory.logicnode.ObjectNode(this, "")]);
		_RemoveObject.addInput(_SpawnObject, 0);
		_RemoveObject.addInput(_Self_003, 0);
		_RemoveObject.addOutputs([new armory.logicnode.NullNode(this)]);
	}
}
