package arm.node;

@:keep class EnemyAI_S extends armory.logicnode.LogicTree {

	public function new() { super(); notifyOnAdd(add); }

	override public function add() {
		var _ApplyImpulse_001 = new armory.logicnode.ApplyImpulseNode(this);
		var _SpawnObject = new armory.logicnode.SpawnObjectNode(this);
		var _Gate_003 = new armory.logicnode.GateNode(this);
		_Gate_003.property0 = "Greater";
		_Gate_003.property1 = 9.999999747378752e-05;
		var _Gate_002 = new armory.logicnode.GateNode(this);
		_Gate_002.property0 = "Equal";
		_Gate_002.property1 = 9.999999747378752e-05;
		var _OnUpdate = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate.addOutputs([_Gate_002]);
		_Gate_002.addInput(_OnUpdate, 0);
		var _CastPhysicsRay = new armory.logicnode.CastPhysicsRayNode(this);
		var _GetLocation = new armory.logicnode.GetLocationNode(this);
		var _GetChild_001 = new armory.logicnode.GetChildNode(this);
		var _Self_003 = new armory.logicnode.SelfNode(this);
		_Self_003.addOutputs([_GetChild_001]);
		_GetChild_001.addInput(_Self_003, 0);
		_GetChild_001.addInput(new armory.logicnode.StringNode(this, "EnemyGun"), 0);
		_GetChild_001.addOutputs([_GetLocation]);
		_GetLocation.addInput(_GetChild_001, 0);
		_GetLocation.addOutputs([_CastPhysicsRay]);
		_CastPhysicsRay.addInput(_GetLocation, 0);
		var _GetLocation_001 = new armory.logicnode.GetLocationNode(this);
		var _Object = new armory.logicnode.ObjectNode(this);
		_Object.addInput(new armory.logicnode.ObjectNode(this, "Jet"), 0);
		_Object.addOutputs([_GetLocation_001, _Gate_002]);
		_GetLocation_001.addInput(_Object, 0);
		_GetLocation_001.addOutputs([_CastPhysicsRay]);
		_CastPhysicsRay.addInput(_GetLocation_001, 0);
		_CastPhysicsRay.addOutputs([_Gate_002]);
		_CastPhysicsRay.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_Gate_002.addInput(_CastPhysicsRay, 0);
		_Gate_002.addInput(_Object, 0);
		_Gate_002.addOutputs([_Gate_003]);
		_Gate_002.addOutputs([new armory.logicnode.NullNode(this)]);
		_Gate_003.addInput(_Gate_002, 0);
		var _Time = new armory.logicnode.TimeNode(this);
		var _Math = new armory.logicnode.MathNode(this);
		_Math.property0 = "Add";
		_Math.property1 = "false";
		_Math.addInput(_Time, 0);
		var _Math_001 = new armory.logicnode.MathNode(this);
		_Math_001.property0 = "Divide";
		_Math_001.property1 = "false";
		_Math_001.addInput(new armory.logicnode.FloatNode(this, 1.0), 0);
		var _Random_Float_ = new armory.logicnode.RandomFloatNode(this);
		_Random_Float_.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Random_Float_.addInput(new armory.logicnode.FloatNode(this, 2.0), 0);
		_Random_Float_.addOutputs([_Math_001]);
		_Math_001.addInput(_Random_Float_, 0);
		_Math_001.addOutputs([_Math]);
		_Math.addInput(_Math_001, 0);
		var _SetVariable = new armory.logicnode.SetVariableNode(this);
		_SetVariable.addInput(_Gate_003, 0);
		var _Float = new armory.logicnode.FloatNode(this);
		_Float.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Float.addOutputs([_SetVariable, _Gate_003]);
		_SetVariable.addInput(_Float, 0);
		_SetVariable.addInput(_Math, 0);
		_SetVariable.addOutputs([new armory.logicnode.NullNode(this)]);
		_Math.addOutputs([_SetVariable]);
		_Time.addOutputs([_Math, _Gate_003]);
		_Time.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Gate_003.addInput(_Time, 0);
		_Gate_003.addInput(_Float, 0);
		_Gate_003.addOutputs([_SetVariable, _SpawnObject]);
		_Gate_003.addOutputs([new armory.logicnode.NullNode(this)]);
		_SpawnObject.addInput(_Gate_003, 0);
		_SpawnObject.addInput(new armory.logicnode.ObjectNode(this, "EnemyLaser"), 0);
		var _GetTransform = new armory.logicnode.GetTransformNode(this);
		var _GetChild = new armory.logicnode.GetChildNode(this);
		var _Self_002 = new armory.logicnode.SelfNode(this);
		_Self_002.addOutputs([_GetChild]);
		_GetChild.addInput(_Self_002, 0);
		_GetChild.addInput(new armory.logicnode.StringNode(this, "EnemyGun"), 0);
		_GetChild.addOutputs([_GetTransform]);
		_GetTransform.addInput(_GetChild, 0);
		_GetTransform.addOutputs([_SpawnObject]);
		_SpawnObject.addInput(_GetTransform, 0);
		var _SetParent = new armory.logicnode.SetParentNode(this);
		_SetParent.addInput(_SpawnObject, 0);
		_SetParent.addInput(_SpawnObject, 1);
		_SetParent.addInput(new armory.logicnode.ObjectNode(this, "EnemyLasers"), 0);
		_SetParent.addOutputs([new armory.logicnode.NullNode(this)]);
		_SpawnObject.addOutputs([_ApplyImpulse_001, _SetParent]);
		_SpawnObject.addOutputs([_ApplyImpulse_001, _SetParent]);
		_ApplyImpulse_001.addInput(_SpawnObject, 0);
		_ApplyImpulse_001.addInput(_SpawnObject, 1);
		var _VectorMath_005 = new armory.logicnode.VectorMathNode(this);
		_VectorMath_005.property0 = "Multiply";
		var _VectorMath_007 = new armory.logicnode.VectorMathNode(this);
		_VectorMath_007.property0 = "Normalize";
		var _VectorMath_006 = new armory.logicnode.VectorMathNode(this);
		_VectorMath_006.property0 = "Add";
		var _Random_Vector_ = new armory.logicnode.RandomVectorNode(this);
		_Random_Vector_.addInput(new armory.logicnode.VectorNode(this, -0.10000000149011612, -0.10000000149011612, 0.0), 0);
		_Random_Vector_.addInput(new armory.logicnode.VectorNode(this, 0.10000000149011612, 0.10000000149011612, 0.0), 0);
		_Random_Vector_.addOutputs([_VectorMath_006]);
		_VectorMath_006.addInput(_Random_Vector_, 0);
		var _VectorMath_004 = new armory.logicnode.VectorMathNode(this);
		_VectorMath_004.property0 = "Normalize";
		var _VectorMath_003 = new armory.logicnode.VectorMathNode(this);
		_VectorMath_003.property0 = "Add";
		var _GetLocation_003 = new armory.logicnode.GetLocationNode(this);
		_GetLocation_003.addInput(new armory.logicnode.ObjectNode(this, "Jet"), 0);
		_GetLocation_003.addOutputs([_VectorMath_003]);
		_VectorMath_003.addInput(_GetLocation_003, 0);
		var _VectorMath_002 = new armory.logicnode.VectorMathNode(this);
		_VectorMath_002.property0 = "Multiply";
		var _GetLocation_002 = new armory.logicnode.GetLocationNode(this);
		var _Self = new armory.logicnode.SelfNode(this);
		_Self.addOutputs([_GetLocation_002]);
		_GetLocation_002.addInput(_Self, 0);
		_GetLocation_002.addOutputs([_VectorMath_002]);
		_VectorMath_002.addInput(_GetLocation_002, 0);
		_VectorMath_002.addInput(new armory.logicnode.VectorNode(this, -1.0, -1.0, -1.0), 0);
		_VectorMath_002.addOutputs([_VectorMath_003]);
		_VectorMath_002.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_VectorMath_003.addInput(_VectorMath_002, 0);
		_VectorMath_003.addOutputs([_VectorMath_004]);
		_VectorMath_003.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_VectorMath_004.addInput(_VectorMath_003, 0);
		_VectorMath_004.addInput(new armory.logicnode.VectorNode(this, 1.0, 1.0, 1.0), 0);
		_VectorMath_004.addOutputs([_VectorMath_006]);
		_VectorMath_004.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_VectorMath_006.addInput(_VectorMath_004, 0);
		_VectorMath_006.addOutputs([_VectorMath_007]);
		_VectorMath_006.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_VectorMath_007.addInput(_VectorMath_006, 0);
		_VectorMath_007.addInput(new armory.logicnode.VectorNode(this, 1.0, 1.0, 1.0), 0);
		_VectorMath_007.addOutputs([_VectorMath_005]);
		_VectorMath_007.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_VectorMath_005.addInput(_VectorMath_007, 0);
		var _Vector_001 = new armory.logicnode.VectorNode(this);
		var _Integer = new armory.logicnode.IntegerNode(this);
		_Integer.addInput(new armory.logicnode.IntegerNode(this, 25), 0);
		_Integer.addOutputs([_Vector_001, _Vector_001, _Vector_001]);
		_Vector_001.addInput(_Integer, 0);
		_Vector_001.addInput(_Integer, 0);
		_Vector_001.addInput(_Integer, 0);
		_Vector_001.addOutputs([_VectorMath_005]);
		_VectorMath_005.addInput(_Vector_001, 0);
		_VectorMath_005.addOutputs([_ApplyImpulse_001]);
		_VectorMath_005.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_ApplyImpulse_001.addInput(_VectorMath_005, 0);
		_ApplyImpulse_001.addOutputs([new armory.logicnode.NullNode(this)]);
	}
}
