package arm.node;

@:keep class SelfDeath extends armory.logicnode.LogicTree {

	public function new() { super(); notifyOnAdd(add); }

	override public function add() {
		var _SendGlobalEvent_002 = new armory.logicnode.SendGlobalEventNode(this);
		var _Gate_001 = new armory.logicnode.GateNode(this);
		_Gate_001.property0 = "Less Equal";
		_Gate_001.property1 = 9.999999747378752e-05;
		var _SetVariable = new armory.logicnode.SetVariableNode(this);
		var _RemoveObject = new armory.logicnode.RemoveObjectNode(this);
		var _Gate_002 = new armory.logicnode.GateNode(this);
		_Gate_002.property0 = "Equal";
		_Gate_002.property1 = 9.999999747378752e-05;
		var _Gate_003 = new armory.logicnode.GateNode(this);
		_Gate_003.property0 = "Greater Equal";
		_Gate_003.property1 = 9.999999747378752e-05;
		var _OnUpdate = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate.addOutputs([_Gate_003]);
		_Gate_003.addInput(_OnUpdate, 0);
		var _Float = new armory.logicnode.FloatNode(this);
		_Float.addInput(new armory.logicnode.FloatNode(this, 100.0), 0);
		var _Math_002 = new armory.logicnode.MathNode(this);
		_Math_002.property0 = "Subtract";
		_Math_002.property1 = "false";
		_Math_002.addInput(_Float, 0);
		var _GetProperty = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject.addOutputs([_GetProperty]);
		_GetProperty.addInput(_GlobalObject, 0);
		_GetProperty.addInput(new armory.logicnode.StringNode(this, "EnemyDamage"), 0);
		_GetProperty.addOutputs([_Math_002]);
		_Math_002.addInput(_GetProperty, 0);
		_Math_002.addOutputs([_SetVariable]);
		var _SetProperty = new armory.logicnode.SetPropertyNode(this);
		var _OnUpdate_004 = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate_004.addOutputs([_SetProperty]);
		_SetProperty.addInput(_OnUpdate_004, 0);
		var _GlobalObject_001 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_001.addOutputs([_SetProperty]);
		_SetProperty.addInput(_GlobalObject_001, 0);
		_SetProperty.addInput(new armory.logicnode.StringNode(this, "HP"), 0);
		_SetProperty.addInput(_Float, 0);
		_SetProperty.addOutputs([new armory.logicnode.NullNode(this)]);
		_Float.addOutputs([_SetVariable, _Math_002, _Float, _SetProperty, _Gate_001, _Float, _Float]);
		_Gate_003.addInput(_Float, 0);
		var _Float_005 = new armory.logicnode.FloatNode(this);
		_Float_005.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Float_005.addOutputs([_Gate_003]);
		_Gate_003.addInput(_Float_005, 0);
		_Gate_003.addOutputs([_Gate_002]);
		_Gate_003.addOutputs([new armory.logicnode.NullNode(this)]);
		_Gate_002.addInput(_Gate_003, 0);
		var _GetParent = new armory.logicnode.GetParentNode(this);
		var _ArrayGet = new armory.logicnode.ArrayGetNode(this);
		var _GetContacts = new armory.logicnode.GetContactsNode(this);
		var _Self = new armory.logicnode.SelfNode(this);
		_Self.addOutputs([_GetContacts]);
		_GetContacts.addInput(_Self, 0);
		var _ArrayLength = new armory.logicnode.ArrayLengthNode(this);
		_ArrayLength.addInput(_GetContacts, 0);
		var _Math_003 = new armory.logicnode.MathNode(this);
		_Math_003.property0 = "Subtract";
		_Math_003.property1 = "false";
		_Math_003.addInput(_ArrayLength, 0);
		_Math_003.addInput(new armory.logicnode.FloatNode(this, 1.0), 0);
		_Math_003.addOutputs([_ArrayGet]);
		_ArrayLength.addOutputs([_Math_003]);
		_GetContacts.addOutputs([_ArrayLength, _ArrayGet]);
		_ArrayGet.addInput(_GetContacts, 0);
		_ArrayGet.addInput(_Math_003, 0);
		_ArrayGet.addOutputs([_GetParent, _RemoveObject]);
		_GetParent.addInput(_ArrayGet, 0);
		_GetParent.addOutputs([_Gate_002]);
		_Gate_002.addInput(_GetParent, 0);
		var _Object = new armory.logicnode.ObjectNode(this);
		_Object.addInput(new armory.logicnode.ObjectNode(this, "EnemyLasers"), 0);
		_Object.addOutputs([_Gate_002]);
		_Gate_002.addInput(_Object, 0);
		_Gate_002.addOutputs([_RemoveObject]);
		_Gate_002.addOutputs([new armory.logicnode.NullNode(this)]);
		_RemoveObject.addInput(_Gate_002, 0);
		_RemoveObject.addInput(_ArrayGet, 0);
		_RemoveObject.addOutputs([_SetVariable]);
		_SetVariable.addInput(_RemoveObject, 0);
		_SetVariable.addInput(_Float, 0);
		_SetVariable.addInput(_Math_002, 0);
		_SetVariable.addOutputs([_Gate_001]);
		_Gate_001.addInput(_SetVariable, 0);
		_Gate_001.addInput(_Float, 0);
		var _Float_001 = new armory.logicnode.FloatNode(this);
		_Float_001.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Float_001.addOutputs([_Gate_001]);
		_Gate_001.addInput(_Float_001, 0);
		_Gate_001.addOutputs([_SendGlobalEvent_002]);
		_Gate_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_SendGlobalEvent_002.addInput(_Gate_001, 0);
		_SendGlobalEvent_002.addInput(new armory.logicnode.StringNode(this, "Killed"), 0);
		_SendGlobalEvent_002.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetVariable_004 = new armory.logicnode.SetVariableNode(this);
		var _Gate_004 = new armory.logicnode.GateNode(this);
		_Gate_004.property0 = "Less";
		_Gate_004.property1 = 9.999999747378752e-05;
		var _OnUpdate_003 = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate_003.addOutputs([_Gate_004]);
		_Gate_004.addInput(_OnUpdate_003, 0);
		_Gate_004.addInput(_Float, 0);
		var _Float_002 = new armory.logicnode.FloatNode(this);
		_Float_002.addInput(new armory.logicnode.FloatNode(this, 100.0), 0);
		_Float_002.addOutputs([_Gate_004]);
		_Gate_004.addInput(_Float_002, 0);
		_Gate_004.addOutputs([_SetVariable_004]);
		_Gate_004.addOutputs([new armory.logicnode.NullNode(this)]);
		_SetVariable_004.addInput(_Gate_004, 0);
		_SetVariable_004.addInput(_Float, 0);
		var _Math = new armory.logicnode.MathNode(this);
		_Math.property0 = "Add";
		_Math.property1 = "false";
		_Math.addInput(_Float, 0);
		_Math.addInput(new armory.logicnode.FloatNode(this, 0.20000000298023224), 0);
		_Math.addOutputs([_SetVariable_004]);
		_SetVariable_004.addInput(_Math, 0);
		_SetVariable_004.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetVisible_005 = new armory.logicnode.SetVisibleNode(this);
		var _SetVariable_006 = new armory.logicnode.SetVariableNode(this);
		var _IsTrue_002 = new armory.logicnode.IsTrueNode(this);
		var _OnEvent = new armory.logicnode.OnEventNode(this);
		_OnEvent.property0 = "Game Over";
		_OnEvent.addOutputs([_IsTrue_002]);
		_IsTrue_002.addInput(_OnEvent, 0);
		var _Boolean_006 = new armory.logicnode.BooleanNode(this);
		_Boolean_006.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_Boolean_006.addOutputs([_IsTrue_002, _SetVariable_006]);
		_IsTrue_002.addInput(_Boolean_006, 0);
		_IsTrue_002.addOutputs([_SetVariable_006]);
		_SetVariable_006.addInput(_IsTrue_002, 0);
		_SetVariable_006.addInput(_Boolean_006, 0);
		var _Boolean_005 = new armory.logicnode.BooleanNode(this);
		_Boolean_005.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_Boolean_005.addOutputs([_SetVariable_006]);
		_SetVariable_006.addInput(_Boolean_005, 0);
		var _SetVisible_007 = new armory.logicnode.SetVisibleNode(this);
		_SetVisible_007.addInput(_SetVariable_006, 0);
		var _Self_003 = new armory.logicnode.SelfNode(this);
		var _GetTransform_002 = new armory.logicnode.GetTransformNode(this);
		_GetTransform_002.addInput(_Self_003, 0);
		var _SetTransform_002 = new armory.logicnode.SetTransformNode(this);
		_SetTransform_002.addInput(_SetVisible_007, 0);
		_SetTransform_002.addInput(new armory.logicnode.ObjectNode(this, "JetExplosion"), 0);
		_SetTransform_002.addInput(_GetTransform_002, 0);
		var _PlayAction_001 = new armory.logicnode.PlayActionNode(this);
		_PlayAction_001.addInput(_SetTransform_002, 0);
		_PlayAction_001.addInput(new armory.logicnode.ObjectNode(this, "JetExplosion"), 0);
		_PlayAction_001.addInput(new armory.logicnode.StringNode(this, "JetExplosion"), 0);
		_PlayAction_001.addInput(new armory.logicnode.FloatNode(this, 0.20000000298023224), 0);
		_PlayAction_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _PauseAction_001 = new armory.logicnode.PauseActionNode(this);
		_PauseAction_001.addInput(_PlayAction_001, 1);
		_PauseAction_001.addInput(new armory.logicnode.ObjectNode(this, "JetExplosion"), 0);
		var _Shutdown = new armory.logicnode.ShutdownNode(this);
		_Shutdown.addInput(_PauseAction_001, 0);
		_Shutdown.addOutputs([new armory.logicnode.NullNode(this)]);
		_PauseAction_001.addOutputs([_Shutdown]);
		var _SetTransform_003 = new armory.logicnode.SetTransformNode(this);
		_SetTransform_003.addInput(_PlayAction_001, 1);
		_SetTransform_003.addInput(new armory.logicnode.ObjectNode(this, "JetExplosion"), 0);
		var _GetTransform_003 = new armory.logicnode.GetTransformNode(this);
		_GetTransform_003.addInput(new armory.logicnode.ObjectNode(this, "Place"), 0);
		_GetTransform_003.addOutputs([_SetTransform_003]);
		_SetTransform_003.addInput(_GetTransform_003, 0);
		_SetTransform_003.addOutputs([new armory.logicnode.NullNode(this)]);
		_PlayAction_001.addOutputs([_PauseAction_001, _SetTransform_003]);
		var _PlayAction_003 = new armory.logicnode.PlayActionNode(this);
		_PlayAction_003.addInput(_SetTransform_002, 0);
		_PlayAction_003.addInput(new armory.logicnode.ObjectNode(this, "Sphere"), 0);
		_PlayAction_003.addInput(new armory.logicnode.StringNode(this, "SphereAction"), 0);
		_PlayAction_003.addInput(new armory.logicnode.FloatNode(this, 0.20000000298023224), 0);
		_PlayAction_003.addOutputs([new armory.logicnode.NullNode(this)]);
		var _PauseAction_003 = new armory.logicnode.PauseActionNode(this);
		_PauseAction_003.addInput(_PlayAction_003, 1);
		_PauseAction_003.addInput(new armory.logicnode.ObjectNode(this, "Sphere"), 0);
		_PauseAction_003.addOutputs([new armory.logicnode.NullNode(this)]);
		_PlayAction_003.addOutputs([_PauseAction_003]);
		_SetTransform_002.addOutputs([_PlayAction_001, _PlayAction_003]);
		_GetTransform_002.addOutputs([_SetTransform_002]);
		_Self_003.addOutputs([_SetVisible_007, _GetTransform_002]);
		_SetVisible_007.addInput(_Self_003, 0);
		_SetVisible_007.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_SetVisible_007.addOutputs([_SetTransform_002]);
		var _SetVisible_006 = new armory.logicnode.SetVisibleNode(this);
		_SetVisible_006.addInput(_SetVariable_006, 0);
		_SetVisible_006.addInput(new armory.logicnode.ObjectNode(this, "Thruster_R"), 0);
		_SetVisible_006.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_SetVisible_006.addOutputs([new armory.logicnode.NullNode(this)]);
		_SetVariable_006.addOutputs([_SetVisible_007, _SetVisible_005, _SetVisible_006]);
		_SetVisible_005.addInput(_SetVariable_006, 0);
		_SetVisible_005.addInput(new armory.logicnode.ObjectNode(this, "Thruster_L"), 0);
		_SetVisible_005.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_SetVisible_005.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetVisible_003 = new armory.logicnode.SetVisibleNode(this);
		var _OnEvent_001 = new armory.logicnode.OnEventNode(this);
		_OnEvent_001.property0 = "Killed";
		var _SetVisible_002 = new armory.logicnode.SetVisibleNode(this);
		_SetVisible_002.addInput(_OnEvent_001, 0);
		var _Self_002 = new armory.logicnode.SelfNode(this);
		var _GetTransform = new armory.logicnode.GetTransformNode(this);
		_GetTransform.addInput(_Self_002, 0);
		var _SetTransform = new armory.logicnode.SetTransformNode(this);
		_SetTransform.addInput(_SetVisible_002, 0);
		_SetTransform.addInput(new armory.logicnode.ObjectNode(this, "JetExplosion"), 0);
		_SetTransform.addInput(_GetTransform, 0);
		var _PlayAction = new armory.logicnode.PlayActionNode(this);
		_PlayAction.addInput(_SetTransform, 0);
		_PlayAction.addInput(new armory.logicnode.ObjectNode(this, "JetExplosion"), 0);
		_PlayAction.addInput(new armory.logicnode.StringNode(this, "JetExplosion"), 0);
		_PlayAction.addInput(new armory.logicnode.FloatNode(this, 0.20000000298023224), 0);
		_PlayAction.addOutputs([new armory.logicnode.NullNode(this)]);
		var _PauseAction = new armory.logicnode.PauseActionNode(this);
		_PauseAction.addInput(_PlayAction, 1);
		_PauseAction.addInput(new armory.logicnode.ObjectNode(this, "JetExplosion"), 0);
		_PauseAction.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetTransform_001 = new armory.logicnode.SetTransformNode(this);
		_SetTransform_001.addInput(_PlayAction, 1);
		_SetTransform_001.addInput(new armory.logicnode.ObjectNode(this, "JetExplosion"), 0);
		var _GetTransform_001 = new armory.logicnode.GetTransformNode(this);
		_GetTransform_001.addInput(new armory.logicnode.ObjectNode(this, "Place"), 0);
		_GetTransform_001.addOutputs([_SetTransform_001]);
		_SetTransform_001.addInput(_GetTransform_001, 0);
		_SetTransform_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_PlayAction.addOutputs([_PauseAction, _SetTransform_001]);
		var _PlayAction_002 = new armory.logicnode.PlayActionNode(this);
		_PlayAction_002.addInput(_SetTransform, 0);
		_PlayAction_002.addInput(new armory.logicnode.ObjectNode(this, "Sphere"), 0);
		_PlayAction_002.addInput(new armory.logicnode.StringNode(this, "SphereAction"), 0);
		_PlayAction_002.addInput(new armory.logicnode.FloatNode(this, 0.20000000298023224), 0);
		_PlayAction_002.addOutputs([new armory.logicnode.NullNode(this)]);
		var _PauseAction_002 = new armory.logicnode.PauseActionNode(this);
		_PauseAction_002.addInput(_PlayAction_002, 1);
		_PauseAction_002.addInput(new armory.logicnode.ObjectNode(this, "Sphere"), 0);
		_PauseAction_002.addOutputs([new armory.logicnode.NullNode(this)]);
		_PlayAction_002.addOutputs([_PauseAction_002]);
		_SetTransform.addOutputs([_PlayAction, _PlayAction_002]);
		_GetTransform.addOutputs([_SetTransform]);
		_Self_002.addOutputs([_SetVisible_002, _GetTransform]);
		_SetVisible_002.addInput(_Self_002, 0);
		_SetVisible_002.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_SetVisible_002.addOutputs([_SetTransform]);
		var _SetVisible_004 = new armory.logicnode.SetVisibleNode(this);
		_SetVisible_004.addInput(_OnEvent_001, 0);
		_SetVisible_004.addInput(new armory.logicnode.ObjectNode(this, "Thruster_R"), 0);
		_SetVisible_004.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_SetVisible_004.addOutputs([new armory.logicnode.NullNode(this)]);
		var _Sleep_001 = new armory.logicnode.SleepNode(this);
		_Sleep_001.addInput(_OnEvent_001, 0);
		_Sleep_001.addInput(new armory.logicnode.FloatNode(this, 1.0), 0);
		var _SetVisible = new armory.logicnode.SetVisibleNode(this);
		_SetVisible.addInput(_Sleep_001, 0);
		var _Self_001 = new armory.logicnode.SelfNode(this);
		_Self_001.addOutputs([_SetVisible]);
		_SetVisible.addInput(_Self_001, 0);
		_SetVisible.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_SetVisible.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetVisible_008 = new armory.logicnode.SetVisibleNode(this);
		_SetVisible_008.addInput(_Sleep_001, 0);
		_SetVisible_008.addInput(new armory.logicnode.ObjectNode(this, "Thruster_L"), 0);
		_SetVisible_008.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_SetVisible_008.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetVisible_009 = new armory.logicnode.SetVisibleNode(this);
		_SetVisible_009.addInput(_Sleep_001, 0);
		_SetVisible_009.addInput(new armory.logicnode.ObjectNode(this, "Thruster_R"), 0);
		_SetVisible_009.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_SetVisible_009.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetVariable_009 = new armory.logicnode.SetVariableNode(this);
		_SetVariable_009.addInput(_Sleep_001, 0);
		_SetVariable_009.addInput(_Float, 0);
		var _Float_004 = new armory.logicnode.FloatNode(this);
		_Float_004.addInput(new armory.logicnode.FloatNode(this, 100.0), 0);
		_Float_004.addOutputs([_SetVariable_009]);
		_SetVariable_009.addInput(_Float_004, 0);
		_SetVariable_009.addOutputs([new armory.logicnode.NullNode(this)]);
		_Sleep_001.addOutputs([_SetVisible, _SetVisible_008, _SetVisible_009, _SetVariable_009]);
		_OnEvent_001.addOutputs([_SetVisible_002, _SetVisible_004, _SetVisible_003, _Sleep_001]);
		_SetVisible_003.addInput(_OnEvent_001, 0);
		_SetVisible_003.addInput(new armory.logicnode.ObjectNode(this, "Thruster_L"), 0);
		_SetVisible_003.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_SetVisible_003.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SendGlobalEvent = new armory.logicnode.SendGlobalEventNode(this);
		var _Gate = new armory.logicnode.GateNode(this);
		_Gate.property0 = "Equal";
		_Gate.property1 = 9.999999747378752e-05;
		var _OnUpdate_001 = new armory.logicnode.OnUpdateNode(this);
		var _SetProperty_001 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_001.addInput(_OnUpdate_001, 0);
		var _GlobalObject_002 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_002.addOutputs([_SetProperty_001]);
		_SetProperty_001.addInput(_GlobalObject_002, 0);
		_SetProperty_001.addInput(new armory.logicnode.StringNode(this, "Credits"), 0);
		var _Integer = new armory.logicnode.IntegerNode(this);
		_Integer.addInput(new armory.logicnode.IntegerNode(this, 3), 0);
		var _SetVariable_005 = new armory.logicnode.SetVariableNode(this);
		var _OnEvent_002 = new armory.logicnode.OnEventNode(this);
		_OnEvent_002.property0 = "Killed";
		var _SendGlobalEvent_001 = new armory.logicnode.SendGlobalEventNode(this);
		_SendGlobalEvent_001.addInput(_OnEvent_002, 0);
		_SendGlobalEvent_001.addInput(new armory.logicnode.StringNode(this, "-1 Credit"), 0);
		_SendGlobalEvent_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_OnEvent_002.addOutputs([_SendGlobalEvent_001, _SetVariable_005]);
		_SetVariable_005.addInput(_OnEvent_002, 0);
		_SetVariable_005.addInput(_Integer, 0);
		var _Math_004 = new armory.logicnode.MathNode(this);
		_Math_004.property0 = "Subtract";
		_Math_004.property1 = "false";
		_Math_004.addInput(_Integer, 0);
		_Math_004.addInput(new armory.logicnode.FloatNode(this, 1.0), 0);
		_Math_004.addOutputs([_SetVariable_005]);
		_SetVariable_005.addInput(_Math_004, 0);
		_SetVariable_005.addOutputs([new armory.logicnode.NullNode(this)]);
		_Integer.addOutputs([_SetVariable_005, _Math_004, _SetProperty_001, _Gate]);
		_SetProperty_001.addInput(_Integer, 0);
		_SetProperty_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_OnUpdate_001.addOutputs([_SetProperty_001, _Gate]);
		_Gate.addInput(_OnUpdate_001, 0);
		_Gate.addInput(_Integer, 0);
		var _Float_003 = new armory.logicnode.FloatNode(this);
		_Float_003.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Float_003.addOutputs([_Gate]);
		_Gate.addInput(_Float_003, 0);
		_Gate.addOutputs([_SendGlobalEvent]);
		_Gate.addOutputs([new armory.logicnode.NullNode(this)]);
		_SendGlobalEvent.addInput(_Gate, 0);
		_SendGlobalEvent.addInput(new armory.logicnode.StringNode(this, "Game Over"), 0);
		_SendGlobalEvent.addOutputs([new armory.logicnode.NullNode(this)]);
	}
}
