package arm.node;

@:keep class Spawner extends armory.logicnode.LogicTree {

	public function new() { super(); notifyOnAdd(add); }

	override public function add() {
		var _SetParent = new armory.logicnode.SetParentNode(this);
		var _SpawnObject = new armory.logicnode.SpawnObjectNode(this);
		var _SetVariable = new armory.logicnode.SetVariableNode(this);
		var _Gate_004 = new armory.logicnode.GateNode(this);
		_Gate_004.property0 = "Greater";
		_Gate_004.property1 = 9.999999747378752e-05;
		var _Gate_005 = new armory.logicnode.GateNode(this);
		_Gate_005.property0 = "Greater";
		_Gate_005.property1 = 9.999999747378752e-05;
		var _OnUpdate_002 = new armory.logicnode.OnUpdateNode(this);
		var _Gate_007 = new armory.logicnode.GateNode(this);
		_Gate_007.property0 = "Greater";
		_Gate_007.property1 = 9.999999747378752e-05;
		_Gate_007.addInput(_OnUpdate_002, 0);
		var _SeparateXYZ_001 = new armory.logicnode.SeparateVectorNode(this);
		var _GetScale_001 = new armory.logicnode.GetScaleNode(this);
		_GetScale_001.addInput(new armory.logicnode.ObjectNode(this, "Obstacleanim"), 0);
		_GetScale_001.addOutputs([_SeparateXYZ_001]);
		_SeparateXYZ_001.addInput(_GetScale_001, 0);
		_SeparateXYZ_001.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_001.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		var _Math_004 = new armory.logicnode.MathNode(this);
		_Math_004.property0 = "Divide";
		_Math_004.property1 = "false";
		_Math_004.addInput(new armory.logicnode.FloatNode(this, 1.0), 0);
		_Math_004.addInput(_SeparateXYZ_001, 2);
		var _Math_003 = new armory.logicnode.MathNode(this);
		_Math_003.property0 = "Add";
		_Math_003.property1 = "false";
		var _Time_001 = new armory.logicnode.TimeNode(this);
		var _Gate_006 = new armory.logicnode.GateNode(this);
		_Gate_006.property0 = "Greater";
		_Gate_006.property1 = 9.999999747378752e-05;
		_Gate_006.addInput(_Gate_007, 0);
		_Gate_006.addInput(_Time_001, 0);
		var _Float_001 = new armory.logicnode.FloatNode(this);
		_Float_001.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		var _SetVariable_001 = new armory.logicnode.SetVariableNode(this);
		_SetVariable_001.addInput(_Gate_006, 0);
		_SetVariable_001.addInput(_Float_001, 0);
		_SetVariable_001.addInput(_Math_003, 0);
		var _SpawnObject_001 = new armory.logicnode.SpawnObjectNode(this);
		_SpawnObject_001.addInput(_SetVariable_001, 0);
		var _ArrayGet = new armory.logicnode.ArrayGetNode(this);
		var _Array_Object_ = new armory.logicnode.ArrayObjectNode(this);
		_Array_Object_.addInput(new armory.logicnode.ObjectNode(this, "Obstacle 1"), 0);
		_Array_Object_.addInput(new armory.logicnode.ObjectNode(this, "Obstacle 2"), 0);
		_Array_Object_.addInput(new armory.logicnode.ObjectNode(this, "Obstacle 3"), 0);
		_Array_Object_.addOutputs([_ArrayGet]);
		_Array_Object_.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_ArrayGet.addInput(_Array_Object_, 0);
		var _Random_Integer_ = new armory.logicnode.RandomIntegerNode(this);
		_Random_Integer_.addInput(new armory.logicnode.IntegerNode(this, 0), 0);
		_Random_Integer_.addInput(new armory.logicnode.IntegerNode(this, 2), 0);
		_Random_Integer_.addOutputs([_ArrayGet]);
		_ArrayGet.addInput(_Random_Integer_, 0);
		_ArrayGet.addOutputs([_SpawnObject_001]);
		_SpawnObject_001.addInput(_ArrayGet, 0);
		var _Transform = new armory.logicnode.TransformNode(this);
		var _Vector = new armory.logicnode.VectorNode(this);
		var _Random_Float_ = new armory.logicnode.RandomFloatNode(this);
		_Random_Float_.addInput(new armory.logicnode.FloatNode(this, -13.0), 0);
		_Random_Float_.addInput(new armory.logicnode.FloatNode(this, 14.0), 0);
		_Random_Float_.addOutputs([_Vector]);
		_Vector.addInput(_Random_Float_, 0);
		var _Math_002 = new armory.logicnode.MathNode(this);
		_Math_002.property0 = "Add";
		_Math_002.property1 = "false";
		var _SeparateXYZ_002 = new armory.logicnode.SeparateVectorNode(this);
		var _GetLocation = new armory.logicnode.GetLocationNode(this);
		_GetLocation.addInput(new armory.logicnode.ObjectNode(this, "Camera"), 0);
		_GetLocation.addOutputs([_SeparateXYZ_002]);
		_SeparateXYZ_002.addInput(_GetLocation, 0);
		_SeparateXYZ_002.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_002.addOutputs([_Math_002]);
		_SeparateXYZ_002.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Math_002.addInput(_SeparateXYZ_002, 1);
		_Math_002.addInput(new armory.logicnode.FloatNode(this, 45.29999923706055), 0);
		_Math_002.addOutputs([_Vector]);
		_Vector.addInput(_Math_002, 0);
		_Vector.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector.addOutputs([_Transform]);
		_Transform.addInput(_Vector, 0);
		_Transform.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_Transform.addInput(new armory.logicnode.VectorNode(this, 1.0, 1.0, 1.0), 0);
		_Transform.addOutputs([_SpawnObject, _SpawnObject_001]);
		_SpawnObject_001.addInput(_Transform, 0);
		var _SetParent_001 = new armory.logicnode.SetParentNode(this);
		_SetParent_001.addInput(_SpawnObject_001, 0);
		_SetParent_001.addInput(_SpawnObject_001, 1);
		_SetParent_001.addInput(new armory.logicnode.ObjectNode(this, "Obstacles"), 0);
		_SetParent_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _ArrayAdd = new armory.logicnode.ArrayAddNode(this);
		_ArrayAdd.addInput(_SpawnObject_001, 0);
		var _Array_Object__001 = new armory.logicnode.ArrayObjectNode(this);
		var _ArrayShift = new armory.logicnode.ArrayShiftNode(this);
		_ArrayShift.addInput(_Array_Object__001, 0);
		var _RemoveObject = new armory.logicnode.RemoveObjectNode(this);
		var _Sleep = new armory.logicnode.SleepNode(this);
		_Sleep.addInput(_ArrayAdd, 0);
		_Sleep.addInput(new armory.logicnode.FloatNode(this, 10.0), 0);
		_Sleep.addOutputs([_RemoveObject]);
		_RemoveObject.addInput(_Sleep, 0);
		_RemoveObject.addInput(_ArrayShift, 0);
		_RemoveObject.addOutputs([new armory.logicnode.NullNode(this)]);
		_ArrayShift.addOutputs([_RemoveObject]);
		_Array_Object__001.addOutputs([_ArrayAdd, _ArrayShift]);
		_Array_Object__001.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_ArrayAdd.addInput(_Array_Object__001, 0);
		_ArrayAdd.addInput(_SpawnObject_001, 1);
		_ArrayAdd.addOutputs([_Sleep]);
		_SpawnObject_001.addOutputs([_SetParent_001, _ArrayAdd]);
		_SpawnObject_001.addOutputs([_SetParent_001, _ArrayAdd]);
		_SetVariable_001.addOutputs([_SpawnObject_001]);
		_Float_001.addOutputs([_SetVariable_001, _Gate_006]);
		_Gate_006.addInput(_Float_001, 0);
		_Gate_006.addOutputs([_SetVariable_001]);
		_Gate_006.addOutputs([new armory.logicnode.NullNode(this)]);
		_Time_001.addOutputs([_Math_003, _Gate_006]);
		_Time_001.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Math_003.addInput(_Time_001, 0);
		_Math_003.addInput(_Math_004, 0);
		_Math_003.addOutputs([_SetVariable_001]);
		_Math_004.addOutputs([_Math_003]);
		_SeparateXYZ_001.addOutputs([_Gate_007, _Math_004]);
		_Gate_007.addInput(_SeparateXYZ_001, 2);
		var _Float_002 = new armory.logicnode.FloatNode(this);
		_Float_002.addInput(new armory.logicnode.FloatNode(this, 1.0), 0);
		_Float_002.addOutputs([_Gate_005, _Gate_007]);
		_Gate_007.addInput(_Float_002, 0);
		_Gate_007.addOutputs([_Gate_006]);
		_Gate_007.addOutputs([new armory.logicnode.NullNode(this)]);
		_OnUpdate_002.addOutputs([_Gate_005, _Gate_007]);
		_Gate_005.addInput(_OnUpdate_002, 0);
		var _SeparateXYZ = new armory.logicnode.SeparateVectorNode(this);
		var _GetScale = new armory.logicnode.GetScaleNode(this);
		_GetScale.addInput(new armory.logicnode.ObjectNode(this, "Enemyanim"), 0);
		_GetScale.addOutputs([_SeparateXYZ]);
		_SeparateXYZ.addInput(_GetScale, 0);
		_SeparateXYZ.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		var _Math_001 = new armory.logicnode.MathNode(this);
		_Math_001.property0 = "Divide";
		_Math_001.property1 = "false";
		_Math_001.addInput(new armory.logicnode.FloatNode(this, 1.0), 0);
		_Math_001.addInput(_SeparateXYZ, 2);
		var _Math = new armory.logicnode.MathNode(this);
		_Math.property0 = "Add";
		_Math.property1 = "false";
		var _Time = new armory.logicnode.TimeNode(this);
		_Time.addOutputs([_Math, _Gate_004]);
		_Time.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Math.addInput(_Time, 0);
		_Math.addInput(_Math_001, 0);
		_Math.addOutputs([_SetVariable]);
		_Math_001.addOutputs([_Math]);
		_SeparateXYZ.addOutputs([_Math_001, _Gate_005]);
		_Gate_005.addInput(_SeparateXYZ, 2);
		_Gate_005.addInput(_Float_002, 0);
		_Gate_005.addOutputs([_Gate_004]);
		_Gate_005.addOutputs([new armory.logicnode.NullNode(this)]);
		_Gate_004.addInput(_Gate_005, 0);
		_Gate_004.addInput(_Time, 0);
		var _Float = new armory.logicnode.FloatNode(this);
		_Float.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Float.addOutputs([_SetVariable, _Gate_004]);
		_Gate_004.addInput(_Float, 0);
		_Gate_004.addOutputs([_SetVariable]);
		_Gate_004.addOutputs([new armory.logicnode.NullNode(this)]);
		_SetVariable.addInput(_Gate_004, 0);
		_SetVariable.addInput(_Float, 0);
		_SetVariable.addInput(_Math, 0);
		_SetVariable.addOutputs([_SpawnObject]);
		_SpawnObject.addInput(_SetVariable, 0);
		_SpawnObject.addInput(new armory.logicnode.ObjectNode(this, "ENimi0"), 0);
		_SpawnObject.addInput(_Transform, 0);
		_SpawnObject.addOutputs([_SetParent]);
		_SpawnObject.addOutputs([_SetParent]);
		_SetParent.addInput(_SpawnObject, 0);
		_SetParent.addInput(_SpawnObject, 1);
		_SetParent.addInput(new armory.logicnode.ObjectNode(this, "Enemies"), 0);
		_SetParent.addOutputs([new armory.logicnode.NullNode(this)]);
	}
}
